logger_level: Logger::INFO

#### Browser driver configs ####

webdriver:
  browser: chrome
  headless: false
  chrome_profile: true
  chrome_optional_profile: false
  firefox_profile: profile

timeouts:
  click_wait: 0.5
  event_wait: 0
  short: 8
  medium: 30
  long: 120
  canvas_poller: 60

#### Test user accounts ####

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  super_admin_canvas_id: secret
  ets_qa_username: secret
  ets_qa_password: secret
  test_user_password: secret
  oski_uid: secret
  gmail_password: secret

#### Test environment configs ####

boac:
  base_url: https://boac-qa.berkeley.edu
  password: secret
  term: Summer 2018
  term_code: 2185
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  tooltips: true
  nessie_scores: true
  nessie_assignments: true

  test_dept: UWASC
  test_coe_advisor_uid: 123456

  assignments_team: GOM
  assignments_max_users: 10
  assignments_term: Spring 2018

  class_page_team: GOW
  class_page_max_users: 5

  curated_group_team: BAM

  last_activity_team: TNM
  last_activity_max_users: 3
  last_activity_context: false

  navigation_team: FBM

  sis_data_team: FBM
  sis_data_max_users: 100

  user_search_team: TNW
  user_search_max_users: 50

cal_net:
  base_url: https://auth-test.berkeley.edu

canvas:
  base_url: https://ucberkeley.test.instructure.com
  admin_sub_account: secret
  uc_berkeley_sub_account: secret
  official_courses_sub_account: secret
  qa_sub_account: secret
  enrollment_retries: 20
  create_site_tool: secret
  course_add_user_tool: secret
  course_captures_tool: secret
  rosters_tool: secret
  official_sections_tool: secret
  mailing_lists_tool: secret
  mailing_list_tool: secret
  e_grades_export_tool: secret

junction:
  base_url: https://junction-qa.berkeley.edu
  basic_auth_password: secret
  background_job_attempts: 500
  background_job_multiplier: 1
  admin_uid: secret

lrs:
  base_url: https://app-qa.ets-berkeley-cloudlrs.net
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  script_loops: 10
  event_time_discrep_seconds: 2

nessie:
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  canvas_data_lag_hours: 24
  include_caliper_tests: false
  caliper_time_margin: 120

oec:
  term: 2018-C
  blue_project_title: 'Summer 2018 Evaluations'
  first_name: secret
  last_name: secret
  uid: secret
  sis_id: secret
  email: secret

salesforce:
  base_url: https://test.salesforce.com
  username: secret
  password: secret

suite_c:
  base_url: https://app-qa.ets-berkeley-suitec.net
  lti_key: secret
  lti_secret: secret
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  poller_retries: 10
  acceptable_events_diff: 0.03
