logger_level: Logger::INFO

#### Browser driver configs ####

webdriver:
  browser: chrome
  headless: false
  chrome_profile: true
  chrome_optional_profile: false
  w3c: false

timeouts:
  click_wait: 0.5
  event_wait: 0
  short: 8
  medium: 30
  long: 120
  canvas_poller: 60
  boac_poller: 12

#### Test user accounts ####

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  super_admin_canvas_id: secret
  ets_qa_username: secret
  ets_qa_password: secret
  test_user_password: secret
  oski_uid: secret

#### Test environment configs ####

# If BOAC is running on your workstation (e.g., you are a developer doing DevOps)
# then set 'api_base_url: http://localhost:5000'. Otherwise, keep 'api_base_url' and 'base_url' equal.
boac:
  api_base_url: https://boa-qa.berkeley.edu
  base_url: https://boa-qa.berkeley.edu
  password: secret
  term: Summer 2018
  term_code: 2185
  term_start_date: 2019-01-21
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  tooltips: true
  nessie_scores: true
  nessie_assignments: true

  test_dept: UWASC
  test_default_cohort_major: [History BA]
  test_add_edit_uid: secret
  test_add_remove_scheduler: secret

  shuffle_max_users: true
  appts_drop_in_dept: QCADV
  assignments_max_users: 10
  assignments_term: Spring 2018
  class_page_max_users: 5
  class_page_max_classmates: 10
  group_bulk_sids_max: 200
  last_activity_max_users: 3
  last_activity_context: false
  no_activity_alert_threshold: 14
  notes_batch_curated_group_count: 2
  notes_batch_students_count: 3
  notes_batch_students_per_group_count: 3
  notes_max_users: 5
  search_max_searches: 10
  search_max_users: 20
  search_word_count: 7
  sis_data_max_users: 100
  service_announcement: 'A service announcement'

cal_net:
  base_url: https://auth-test.berkeley.edu

canvas:
  base_url: https://ucberkeley.test.instructure.com
  admin_sub_account: secret
  uc_berkeley_sub_account: secret
  official_courses_sub_account: secret
  qa_sub_account: secret
  enrollment_retries: 25
  create_site_tool: secret
  course_add_user_tool: secret
  course_captures_tool: secret
  rosters_tool: secret
  official_sections_tool: secret
  mailing_lists_tool: secret
  mailing_list_tool: secret
  e_grades_export_tool: secret

junction:
  base_url: https://junction-qa.berkeley.edu
  basic_auth_password: secret
  background_job_attempts: 500
  background_job_multiplier: 1
  admin_uid: secret

lrs:
  base_url: https://app-qa.ets-berkeley-cloudlrs.net
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  script_loops: 10
  event_time_discrep_seconds: 2

nessie:
  pg_db_host: secret
  pg_db_port: secret
  pg_db_name: secret
  pg_db_user: secret
  pg_db_password: secret
  redshift_db_host: secret
  redshift_db_port: secret
  redshift_db_name: secret
  redshift_db_user: secret
  redshift_db_password: secret
  canvas_data_lag_hours: 24
  include_caliper_tests: false
  caliper_time_margin: 120
  include_l_and_s: false

oec:
  term: 2018-C
  blue_project_title: 'Summer 2018 Evaluations'
  first_name: secret
  last_name: secret
  uid: secret
  sis_id: secret
  email: secret

salesforce:
  base_url: https://test.salesforce.com
  username: secret
  password: secret

suite_c:
  base_url: https://app-qa.ets-berkeley-suitec.net
  lti_key: secret
  lti_secret: secret
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  poller_retries: 10
  acceptable_events_diff: 0.03
