logger_level: Logger::INFO

#### Browser driver configs ####

webdriver:
  browser: chrome
  headless: false
  chrome_profile: true
  chrome_optional_profile: false

timeouts:
  click_wait: 0.5
  short: 8
  medium: 30
  long: 120
  canvas_poller: 60
  boac_poller: 12

#### Test user accounts ####

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  super_admin_canvas_id: secret
  ets_qa_username: secret
  ets_qa_password: secret
  test_user_password: secret
  oski_uid: secret

#### Test environment configs ####

# If BOAC is running on your workstation (e.g., you are a developer doing DevOps)
# then set 'api_base_url: http://localhost:5000'. Otherwise, keep 'api_base_url' and 'base_url' equal.
boac:
  api_base_url: https://boa-qa.berkeley.edu
  base_url: https://boa-qa.berkeley.edu
  password: secret
  term: Summer 2018
  term_code: 2185
  term_start_date: 2019-01-21
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret

  test_default_cohort_major: [History BA]
  test_degree_progress_major: [Bioengineering BS]
  test_add_edit_uid: secret

  class_page_max_users: 1
  class_page_max_classmates: 3
  class_page_max_size: 200
  group_bulk_sids_max: 200
  notes_batch_curated_group_count: 2
  notes_batch_students_count: 3
  notes_max_notes: 2
  notes_max_users: 1
  search_max_searches: 2
  search_max_users: 1
  search_word_count: 4
  sis_data_max_users: 10
  service_announcement: 'A service announcement'

cal_net:
  base_url: https://auth-test.berkeley.edu

canvas:
  base_url: https://ucberkeley.test.instructure.com
  admin_sub_account: secret
  uc_berkeley_sub_account: secret
  official_courses_sub_account: secret
  qa_sub_account: secret
  enrollment_retries: 25
  create_site_tool: secret
  course_add_user_tool: secret
  course_captures_tool: secret
  rosters_tool: secret
  official_sections_tool: secret
  mailing_lists_tool: secret
  mailing_list_tool: secret
  e_grades_export_tool: secret
  user_prov_tool: secret

junction:
  base_url: https://junction-qa.berkeley.edu
  basic_auth_password: secret
  background_job_attempts: 500
  background_job_multiplier: 1
  admin_uid: secret
  oec_uid: secret
  term_name: 'Fall 2021'
  term: '2021-D'
  sis_update_date: '2020-01-01'
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret

lrs:
  base_url: https://app-qa.ets-berkeley-cloudlrs.net
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  script_loops: 10
  event_time_discrep_seconds: 2

nessie:
  pg_db_host: secret
  pg_db_port: secret
  pg_db_name: secret
  pg_db_user: secret
  pg_db_password: secret

oec:
  term: 2018-C
  blue_project_title: 'Summer 2018 Evaluations'
  first_name: secret
  last_name: secret
  uid: secret
  sis_id: secret
  email: secret

ripley:
  base_url: https://ripley-qa.ets.berkeley.edu
  dev_auth_password: secret
  admin_uid: secret
  term_name: 'Spring 2023'
  term_code: '2023-B'
  term_sis_id: '2232'
  sis_update_date: '2020-01-01'
  course_prefixes: ['ECON C', 'CHEM 1A', 'LEGALST']
  e_grades_site_ids: ['123', '456', '789']
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret

squiggy:
  base_url: tbd
  password: secret
  dev_auth_user_id: secret
  dev_auth_password: secret
  lti_key: secret
  lti_secret: secret
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  poller_retries: 10
  load_test_reps: 10
  whiteboards: [123, 456, 789]
